/**
 * Property-Based Tests for Ghostwriter Agent v2
 *
 * Feature: agent-model-v2
 * Properties 11 & 12: Chapter structure coverage and source chunk annotation validity
 *
 * Tests the categorizeMemories function and validates that:
 * - All non-private memories are assigned to at least one chapter category
 * - All category keys are from the valid set
 * - All memory IDs in categorized results reference valid input memories
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import type { Memory, ChapterCategory } from '../types';
import { categorizeMemories, CHAPTER_CATEGORIES } from './ghostwriter';

// ─── Generators ──────────────────────────────────────────────────────────────

const VALID_CATEGORIES: ChapterCategory[] = ['어린시절', '가족', '직업', '전환점', '전하고싶은말'];

/** Korean keywords that help trigger category matching */
const KOREAN_TOPIC_KEYWORDS = [
  '학교', '어린', '가족', '어머니', '아버지', '직장', '회사',
  '전환', '변화', '조언', '교훈', '결혼', '친구', '동네',
  '사업', '퇴직', '이사', '감사', '추억', '여행',
];

/**
 * Generates a valid non-private Memory object for property testing.
 * Uses a mix of Korean keywords in topics to exercise categorization logic.
 */
const nonPrivateMemoryArb: fc.Arbitrary<Memory> = fc.record({
  id: fc.uuid(),
  date: fc.integer({ min: 1940, max: 2024 }).map((year) => `${year}-06-15`),
  topic: fc.tuple(
    fc.constantFrom(...KOREAN_TOPIC_KEYWORDS),
    fc.string({ minLength: 1, maxLength: 20 })
  ).map(([keyword, suffix]) => `${keyword} ${suffix}`),
  originalTranscript: fc.string({ minLength: 10, maxLength: 200 }),
  cleanedTranscript: fc.string({ minLength: 10, maxLength: 200 }),
  publishVersion: fc.string({ minLength: 5, maxLength: 100 }),
  tags: fc.record({
    people: fc.array(fc.string({ minLength: 1, maxLength: 10 }), { minLength: 0, maxLength: 4 }),
    places: fc.array(fc.string({ minLength: 1, maxLength: 10 }), { minLength: 0, maxLength: 4 }),
    emotions: fc.array(
      fc.constantFrom('자부심', '후회', '상실', '감사', '기쁨', '슬픔'),
      { minLength: 0, maxLength: 3 }
    ),
    timePeriod: fc.constantFrom(
      '1940년대', '1950년대', '1960년대', '1970년대', '1980년대',
      '1990년대', '2000년대', '2010년대', '2020년대'
    ),
  }),
  privacy: fc.constantFrom('public' as const, 'family' as const),
  confidenceLabel: fc.constantFrom('확인됨' as const, '추정' as const, '추가 확인 필요' as const),
  contradictions: fc.array(fc.uuid(), { minLength: 0, maxLength: 2 }),
  consent: fc.record({
    status: fc.constantFrom('granted' as const, 'revoked' as const),
    accessTier: fc.constantFrom('본인만' as const, '지정 가족' as const, '전체 가족' as const),
    designatedFamilyIds: fc.array(fc.uuid(), { minLength: 0, maxLength: 3 }),
    lastModified: fc.constant('2024-01-15T10:00:00.000Z'),
  }),
  embedding: fc.constant(null),
});

/**
 * Generates an array of at least 5 non-private Memory objects.
 */
const memoriesArrayArb = fc.array(nonPrivateMemoryArb, { minLength: 5, maxLength: 25 });

// ─── Property 11: Chapter structure covers all non-private memories ──────────

/**
 * Feature: agent-model-v2, Property 11: Chapter structure covers all non-private memories
 *
 * For any set of non-private memories (≥5), the chapter structure generated by the
 * Ghostwriter Agent SHALL assign every non-private memory to at least one chapter,
 * and every chapter category SHALL be from {어린시절, 가족, 직업, 전환점, 전하고싶은말}.
 *
 * **Validates: Requirements 4.1**
 */
describe('Property 11: Chapter structure covers all non-private memories', () => {
  it('every non-private memory ID appears in at least one category', () => {
    fc.assert(
      fc.property(
        memoriesArrayArb,
        (memories) => {
          const result = categorizeMemories(memories);

          // Collect all assigned memory IDs across all categories
          const allAssignedIds = new Set(
            Object.values(result).flat()
          );

          // Every non-private memory must appear in at least one category
          for (const memory of memories) {
            if (memory.privacy !== 'private') {
              expect(allAssignedIds.has(memory.id)).toBe(true);
            }
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('all category keys are from the valid set {어린시절, 가족, 직업, 전환점, 전하고싶은말}', () => {
    fc.assert(
      fc.property(
        memoriesArrayArb,
        (memories) => {
          const result = categorizeMemories(memories);

          const validCategorySet = new Set<string>(VALID_CATEGORIES);
          const resultKeys = Object.keys(result);

          // Every key in the result must be a valid category
          for (const key of resultKeys) {
            expect(validCategorySet.has(key)).toBe(true);
          }

          // The result must contain exactly the 5 valid categories
          expect(resultKeys.length).toBe(5);
          for (const cat of VALID_CATEGORIES) {
            expect(result).toHaveProperty(cat);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ─── Property 12: Source chunk annotations reference valid memories ───────────

/**
 * Feature: agent-model-v2, Property 12: Source chunk annotations reference valid memories
 *
 * For any chapter narrative produced by the Ghostwriter Agent, all memory IDs in
 * source_chunks annotations SHALL exist in the input memory set provided to the Ghostwriter.
 *
 * **Validates: Requirements 4.4**
 */
describe('Property 12: Source chunk annotations reference valid memories', () => {
  it('all memory IDs in categorized result are from the input memory set', () => {
    fc.assert(
      fc.property(
        memoriesArrayArb,
        (memories) => {
          const result = categorizeMemories(memories);

          // Build the set of valid input memory IDs (non-private only, since categorize filters)
          const validInputIds = new Set(
            memories
              .filter((m) => m.privacy !== 'private')
              .map((m) => m.id)
          );

          // Every memory ID in the categorized result must exist in the input set
          for (const category of VALID_CATEGORIES) {
            const assignedIds = result[category];
            for (const id of assignedIds) {
              expect(validInputIds.has(id)).toBe(true);
            }
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('no phantom memory IDs are introduced during categorization', () => {
    fc.assert(
      fc.property(
        memoriesArrayArb,
        (memories) => {
          const result = categorizeMemories(memories);

          // Collect all IDs from the result
          const allResultIds = new Set(Object.values(result).flat());

          // Collect all non-private input IDs
          const inputIds = new Set(
            memories
              .filter((m) => m.privacy !== 'private')
              .map((m) => m.id)
          );

          // Result IDs must be a subset of input IDs (no fabricated IDs)
          for (const id of allResultIds) {
            expect(inputIds.has(id)).toBe(true);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});
